import { format } from "PatternUtils";


/** 背景 地点 时间 等非主体角色因素 */
export const patterns = [
    "building",
    "city",
    "sky",
    "underwater",
    "skyscraper",
    "cityscape",
    "outdoors",
    "railing",
    "air bubble",
    "bubble",
    /^.+ background$/,
    "day",
    "blue sky",
    "cloud",
    "window",
    "blurry",
    "indoors",
    "moon",
    "bird",
    "crow",
    "dragon",
    "full moon",
    "sun",
    "night",
    "moonlight",
    "sunset",
    "explosion",
    "orange sky",
    "burning",
    "embers",
    "molten rock",
    "twilight",
    "ruins",
    "evening",
    "torch",
    "dusk",
    "red sky",
    "sunrise",
    "yellow sky",
    "gradient sky",
    "campfire",
    "cloudy sky",
    "light rays",
    "volcano",
    "fireplace",
    "autumn",
    "destruction",
    "water",
    "ocean",
    "night sky",
    /^star \(sky\)$/,
    "starry sky",
    "curtains",
    "stairs",
    "grass",
    "rain",
    "lotus",
    "lily pad",
    "spider lily",
    "train",
    "ground vehicle",
    "military",
    "afloat",
    "freediving",
    "swimming",
    "letterboxed",
    "mirror",
    "fireworks",
    "fire",
    "sketch",
    "depth of field",
    "sunlight",
    "field",
    "flower field",
    "red moon","forest","nature","tachi-e",
    "confetti",
    "fake screenshot",
    "road",
    "train station",
    "train interior",
    "city lights",
    "real world location", "street", "fence",
    "checkered flag",
    "on vehicle",
    "car", "sports car",
    "classroom", "chalkboard", "school", "school desk", "desk", "school chair",
    "wooden floor", "ceiling",
    "candlelight", "tablecloth", "chandelier", "flame", "halloween",
    "graveyard", "bare tree", "tree",
    "tombstone", "castle", "grave",
    "watercraft", "ship", "boat", "horizon", "beach umbrella", "couch","torii",
    "ceiling light", "tiles", "stage", "stage lights",
    "blurry foreground", "bed",
    "on bed", "pet play","armchair",
    "shouji", "darkness", "pillar","throne",
    "smoke", "picture frame", "painting (object)",
    "contrail", "scenery", "leaf",
    "crowd", "faceless", "faceless male", "contemporary",
    "against glass", "bedroom", "bed sheet", "valentine",
    "column", "cage", "skyline", "cherry blossoms",
    "cover page", "doujin cover", "bar (place)","snow",
    "door", "comic", "speech bubble", "wind",
    "bathtub", "bath"
]



