import { format } from "../PatternUtils";


/** 非环境类小物品或是手持物 */
const set = [
    //冷兵器
    "sword",

    //热兵器
    "rifle", /^.+ rifle$/,


    "scope",
    "wand", "fruit",
    "book", "paper",
    "test tube",
    "vial","feathers",
    "pouch", "lantern",
    "weapon","chain",
    "spear","polearm",
    "tray", "pen",
    "cup", "open book",
    "eyewear removed",
    "disposable cup",
    "drinking straw",
    "teacup", "table",
    "card", "playing card",
    "phone", "cellphone","smartphone",
    "chair", "stuffed toy",
    "bell", "stuffed animal",
    "candy", "teddy bear",
    "candy cane", "drinking glass",
    "wine glass", "alcohol",
    "wine","bear","dango",
    "katana", "sheath", "sheathed",
    "bag","paper lantern",
    "hand fan", "microphone",
    "scroll","tanuki","balloon",
    "gun", "handgun", "food",
    "petals","inflatable raft",
    "crab","fork","knife","animal","ball",
    "popsicle","wind chime",
    "paper fan","uchiwa","bottle",
    "innertube","branch","pillow",
    "beads", "staff","lanyard","handbag",
    "umbrella","oil-paper umbrella",
    "calligraphy brush","smoking pipe",
    "bubble tea","motor vehicle","panda",
    "paintbrush","basket",
    "folding fan","folded fan",
    "gift box","box","gift","drone","cane",
    "potted plant","hand mirror","watering can","ice cream",
    "cherry","spoon","bouquet",
    "flaming weapon", "flaming sword",
    "skeleton","cat","black cat","plant",
    "bug", "locker", "trigger discipline", "bolt action", "suppressor",
    "robot", "gem", "blindfold",
    "school bag", "shoulder bag", "bag charm", "charm (object)", "clock", "eraser", "notebook", "pencil", "chalk",
    "banana", "grapes", "candle", "vase", "candlestand", "gold", "plate", "apple", "cross", "bowl",
    "jack-o'-lantern", "pumpkin", "talisman", "ofuda",
    "rope", "red rope", "ghost",
    "bat (animal)", "spikes", "broken chain",
    "orange slice", "orange (fruit)", "cocktail", "cocktail glass", "tropical drink", "circlet", "cushion",
    "drink", "sex toy",
    "carrot", "cable", "signature", "headgear",
    "riding crop", "pointer",
    "orb", "butterfly", "slime (substance)",
    "monster", "creature",
    "treasure chest", "coin", "scepter",
    "drawstring", "can", "zipper pull tab",
    "tablet pc", "computer",
    "stylus", "handheld game console", "lamp", "drawing tablet", "laptop",
    "chocolate", "heart-shaped chocolate", "kiseru",
    "harp", "instrument", "doll", "character doll",
    "gohei", "babydoll", "stool"
]

export const patterns = format(set);
