import { formatPatterns } from "../Utils";
import * as expression from './expression';

/** 姿势 或 某个身体部位的特写 */
const set = [
    ...expression.patterns.any,
    "holding",
    /^holding [^ ]+$/,
    /^hands on own [^ ]+$/,
    "looking at viewer",
    "looking down",
    "standing",
    "full body",
    "lying",
    "on side",
    "one side up",
    "object hug",
    "pillow hug",
    "sitting",
    "hand up",
    "hands up",
    "bird on hand",
    "cleavage cutout",
    "thighs",
    "upper body",
    "collarbone",
    "navel",
    "stomach",
    "sweat",
    "heart",
    "straight-on",
    "ass visible through thighs",
    "leg up",
    "ass",
    "v-shaped eyebrows",
    "arm up",
    "looking back",
    "out of frame",
    "hand on own chest",
    "own hands together",
    "interlocked fingers",
    "fingers together",
    "own hands clasped",
    "waving",
    "hand on hip",
    "hands on own chest",
    "clenched hands",
    "arm behind head",
    "arm behind back",
    "v arms",
    "on back",
    "hugging own legs",
    "knees up",
    "crossed arms",
    "crossed legs",
    "peeking out",
    "arm under breasts",
    "dual wielding",
    "leaning forward",
    "indian style",
    "partially submerged",
    "floating hair",
    "claw pose",
    "all fours",
    "zettai ryouiki",
    "facing viewer",
    "sweatdrop",
    "armpits",
    "two side up",
    "finger to mouth", "ninja",
    "mouth hold",
    "between breasts",
    "cleavage",
    "flying sweatdrops",
    "walking",
    "knee up",
    "wiping tears",
    "covered navel",
    "looking to the side",
    "on floor",
    "drinking",
    "fellatio gesture",
    "floating",
    "outstretched arms",
    "thigh gap",
    "hand on own chin",
    "arms up",
    "squatting",
    "looking away",
    "standing on one leg",
    "clothes lift",
    "skirt lift",
    "feet out of frame",
    "legs apart",
    "arm support",
    "spread pussy",
    "spread legs", "presenting", "tail raised", "leaning back",
    "sitting on desk", "on desk", "sitting on table", "head tilt",
    "sitting backwards", "bent over",
    "bdsm", "bound",
    "bondage", "shibari","restrained", "bound wrists",
    "bound arms", "bound legs",
    "yokozuwari","paw pose",
    "knees together feet apart", "w arms",
    "object insertion", "vaginal object insertion", "anal object insertion",
    "upside-down", "falling", "legs up", "shoe dangle", "hanging", "hand between legs", "plantar flexion",
    "lifted by self", "dress lift", "foot out of frame", "skirt hold",
    "viewer holding leash", "selfie", "reaching towards viewer", "outstretched arm", "leash pull", "clenched hand",
    "gaping", "on chair", "reclining",
    "footjob",
    "stepped on", "ankle grab", "arm grab", "leg lift", "leg grab", "arms at sides",
    "hand on own face", "head rest", "hand on own cheek",
    "hand in pocket", "arm at side", "breast grab", "molestation", "fingering", "groping",
    "grabbing", "grabbing from behind",
    "on stomach", "the pose", "feet up", "profile",
    "imminent penetration", "imminent vaginal", "buttjob", "two-footed footjob","crossed ankles",
    "holding smoking pipe", "wariza", "v",
    "sex","sex from behind","standing sex","hands on hips",
    "spread ass", "top-down bottom-up", "hand on own ass",
    "looking through legs", "ass grab", "shirt lift", "grabbing own ass"
]
export const patterns = formatPatterns(set);
