import { format } from "PatternUtils";

/** 姿势 或 某个身体部位的特写 */
export const patterns = [
    //身体状态
    "breasts on glass",
    "bouncing breasts",
    "facing away", "arched back",
    "breast rest",
    "gagged", "covered eyes",

    //体位
    "doggystyle",
    "dildo riding",
    "double penetration",
    "sex","sex from behind","standing sex",
    "girl on top",
    "footjob", "buttjob", "two-footed footjob",
    "imminent penetration", "imminent vaginal",

    //目光方向
    "looking up",
    "looking at viewer",
    "looking down",
    "looking through legs",
    "looking at another",
    "looking away",
    "looking to the side",
    "looking back",

    //位置
    "in box", "in container",

    //手部动作
    "hand up",
    "hands up",
    "own hands together",
    "own hands clasped",
    "clenched hands",
    "hand between legs",
    "paw pose", "claw pose",

    //手臂动作
    "arm at side", "outstretched arm", "arms at sides",
    "w arms",  "bound arms",
    "outstretched arms", "arms up",
    "arm support", "armpits",
    "arm up", "arm behind head",
    "arm behind back", "v arms",
    "crossed arms", "arm under breasts",

    //腿部动作
    "knee up","kneeling",
    "knees up", "knees together feet apart",
    "hugging own legs",
    "crossed legs","leg lift",
    "leg up", "legs up", "bound legs",
    "spread legs",
    "legs apart",
    "standing on one leg",

    //主体姿势
    "walking",
    "on side",
    "standing",
    "lying",
    "sitting",
    "on back",
    "squatting",
    "carrying", "hug",

    "straight-on",
    "ass visible through thighs",
    "interlocked fingers",
    "fingers together",
    "waving",
    "peeking out",
    "dual wielding",
    "leaning forward",
    "indian style",
    "partially submerged",
    "floating hair",
    "all fours",
    "zettai ryouiki",
    "facing viewer",
    "finger to mouth", "ninja",
    "mouth hold",
    "cleavage",
    "wiping tears",
    "covered navel",
    "on floor",
    "drinking",
    "fellatio gesture",
    "floating",
    "thigh gap",
    "spread pussy","presenting", "tail raised", "leaning back",
    "head tilt",
    "sitting backwards", "bent over",
    "bdsm", "bound",
    "bondage", "shibari","restrained", "bound wrists",
    "yokozuwari",
    "object insertion", "vaginal object insertion", "anal object insertion",
    "upside-down", "falling", "shoe dangle", "hanging", "plantar flexion",
    "viewer holding leash", "selfie", "reaching towards viewer", "leash pull", "clenched hand",
    "gaping", "reclining",
    "stepped on",
    "head rest",
    "molestation", "fingering", "groping",
    "on stomach", "the pose", "feet up", "profile",
    "crossed ankles",
    "holding smoking pipe", "wariza", "v",
    "spread ass", "top-down bottom-up",
    "ballet",
    "piggyback", "straddling", 
    "hug from behind",
    "talking","female masturbation", "masturbation","spread toes","bathing",
    "showering", "against wall",
]
